### 建立 Task

POST http://127.0.0.1:3000/todo
Content-Type: application/json

{
  "title": "Test todo 16"
}

### 查詢所有 Tasks

GET http://127.0.0.1:3000/todo

### 分頁查詢 Tasks

GET http://127.0.0.1:3000/todo?p=1&ps=5


### 篩選 Tasks 分類
GET http://127.0.0.1:3000/todo?p=1&ps=5&type=onlyFinished


### 註冊

POST http://127.0.0.1:3000/auth/signup
Content-Type: application/json

{
  "mobile": "0999999999",
  "password": "999999999"
}

### 登入
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "mobile": "0999999999",
  "password": "999999999"
}

### 更新 Refresh Token
POST http://127.0.0.1:3000/auth/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMmIxYzdjYi1jNGY4LTQyODctYWI5MS01NWM3N2UwNzdmOWYiLCJtb2JpbGUiOiIwOTk5OTk5OTk5IiwiaWF0IjoxNjUwMjY3NTQzLCJleHAiOjE2NTA4NzIzNDN9.kL9xxtsvCKR8P9nBkJfPFp7Sq3E_FrAisHRj4Dn34yo